AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda application func1 webAPI caller.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: func1.lambda_handler
      Runtime: python3.8
      CodeUri: build/func.zip
      Description: AWS Lambda webAPI caller
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
      Tracing: Active
      Layers:
        - !Ref libs
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: my-python-lib
      Description: Dependencies for sample app.
      ContentUri: ../../build/package/.
      CompatibleRuntimes:
        - python3.8